package termokopel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author elawliet
 */
public class Termo_frame extends javax.swing.JFrame {

    Termokopel Termokopel = null;
    private String data1 = "";
    private String data2 = "";

    private void createObjects()
    {
        Termokopel = new Termokopel(this);
    }

    /**
     * Creates new form termo_frame
     */
    public Termo_frame() {
        initComponents();
        createObjects();
        Termokopel.searchForPorts();
    }

    public void RefreshData1() {
        data1+=jData1.getText() + "\n";
        jShowdata.setText(data1);
    }
    public void RefreshData2() {
        data2+=jData2.getText() + "\n";
        jShowdata2.setText(data2);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jShowdata = new javax.swing.JTextArea();
        jDialog2 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jShowdata2 = new javax.swing.JTextArea();
        jConnect = new javax.swing.JButton();
        jListports = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLog = new javax.swing.JTextArea();
        jData1 = new javax.swing.JTextField();
        jData2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSD1 = new javax.swing.JButton();
        jCD1 = new javax.swing.JButton();
        jSD2 = new javax.swing.JButton();
        jCD2 = new javax.swing.JButton();
        jShow1 = new javax.swing.JButton();
        jShow2 = new javax.swing.JButton();

        jDialog1.setTitle("Record Data Suhu");
        jDialog1.setSize(new java.awt.Dimension(247, 300));

        jShowdata.setColumns(20);
        jShowdata.setRows(5);
        jScrollPane3.setViewportView(jShowdata);

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                .addContainerGap())
        );

        jDialog2.setTitle("Record Data Tekanan");
        jDialog2.setSize(new java.awt.Dimension(247, 300));

        jShowdata2.setColumns(20);
        jShowdata2.setRows(5);
        jScrollPane2.setViewportView(jShowdata2);

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Termokopel");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jConnect.setText("Connect");
        jConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnectActionPerformed(evt);
            }
        });

        jLog.setColumns(20);
        jLog.setRows(5);
        jScrollPane1.setViewportView(jLog);

        jData1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        jData2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N

        jLabel1.setText("Suhu");

        jLabel2.setText("Tekanan");

        jSD1.setText("Save");
        jSD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSD1ActionPerformed(evt);
            }
        });

        jCD1.setText("Clear");
        jCD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCD1ActionPerformed(evt);
            }
        });

        jSD2.setText("Save");
        jSD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSD2ActionPerformed(evt);
            }
        });

        jCD2.setText("Clear");
        jCD2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCD2ActionPerformed(evt);
            }
        });

        jShow1.setText("Show");
        jShow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShow1ActionPerformed(evt);
            }
        });

        jShow2.setText("Show");
        jShow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jShow2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jListports, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jConnect))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jShow2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jSD2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCD2))
                                .addComponent(jData2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jShow1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSD1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCD1))
                    .addComponent(jData1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 359, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jConnect)
                    .addComponent(jListports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jShow2)
                    .addComponent(jLabel2)
                    .addComponent(jShow1)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jData1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jData2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSD1)
                    .addComponent(jCD1)
                    .addComponent(jSD2)
                    .addComponent(jCD2))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnectActionPerformed
        // TODO add your handling code here:
        if (Termokopel.getConnected() == false)
        {
            Termokopel.connect();

            if (Termokopel.initIOStream() == true)
            {
                Termokopel.initListener();
                this.jConnect.setText("Disconnect");
                this.jListports.setEnabled(false);
            }
        }
        else {
            Termokopel.disconnect();
            this.jConnect.setText("Connect");            
            this.jListports.setEnabled(true);
        }
    }//GEN-LAST:event_jConnectActionPerformed

    private void jSD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSD1ActionPerformed
        // TODO add your handling code here:
        if (Termokopel.record1) {
            Termokopel.record1=false;
            jSD1.setText("Save");            
        }
        else {
            Termokopel.record1=true;
            jSD1.setText("Stop");        
            jShowdata.setText(data1);
            jDialog1.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jSD1ActionPerformed

    private void jCD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCD1ActionPerformed
        // TODO add your handling code here:
        data1 = "";
        if(jDialog1.isEnabled()) {
            jShowdata.setText(data1);            
        }
    }//GEN-LAST:event_jCD1ActionPerformed

    private void jCD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCD2ActionPerformed
        // TODO add your handling code here:
        data2 = "";
        if(jDialog2.isEnabled()) {
            jShowdata2.setText(data2);            
        }
    }//GEN-LAST:event_jCD2ActionPerformed

    private void jSD2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSD2ActionPerformed
        if (Termokopel.record2) {
            Termokopel.record2=false;
            jSD2.setText("Save");            
        }
        else {
            Termokopel.record2=true;
            jSD2.setText("Stop");        
            jShowdata2.setText(data2);
            jDialog2.setVisible(rootPaneCheckingEnabled);
        }
    }//GEN-LAST:event_jSD2ActionPerformed

    private void jShow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShow1ActionPerformed
        // TODO add your handling code here:
        jShowdata.setText(data1);
        jDialog1.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jShow1ActionPerformed

    private void jShow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jShow2ActionPerformed
        // TODO add your handling code here:
        jShowdata2.setText(data2);
        jDialog2.setVisible(rootPaneCheckingEnabled);
    }//GEN-LAST:event_jShow2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Termo_frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
                
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Termo_frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCD1;
    private javax.swing.JButton jCD2;
    private javax.swing.JButton jConnect;
    public javax.swing.JTextField jData1;
    public javax.swing.JTextField jData2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JComboBox<String> jListports;
    public javax.swing.JTextArea jLog;
    private javax.swing.JButton jSD1;
    private javax.swing.JButton jSD2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jShow1;
    private javax.swing.JButton jShow2;
    private javax.swing.JTextArea jShowdata;
    private javax.swing.JTextArea jShowdata2;
    // End of variables declaration//GEN-END:variables
}
